[package]
name = "together"
version = "0.1.0"
authors = ["AlexanderChen1989 <alexanderchenmh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
